
- name: "Default"
  condition:
    default: True
  sheet: Timeline
  fields:
    Time(UTC +0): "${Data.@timestamp}"
    Hostname/IP: "${machine}"
    Data_Source: "${data_type}"
    Raw_Data: "${Data}"
    KuiperID: "${_id}"
    Tag: "${tag_type}"
    Export_Version: "${_Export_Version}"
    Export_Date: "${_Export_Date}"
