FROM redis:7.0.11-bookworm

RUN apt update && \
    apt install --no-install-recommends -y python3 python3-pip python3-redis python3-requests python3-psutil cron

COPY ./system_health/ /system_health/


COPY ./system_health/crontabs/crontab.redis /etc/cron.d/crontab

RUN chmod 0644 /etc/cron.d/crontab && \
    crontab /etc/cron.d/crontab && \
    touch /var/log/cron_redis.log


CMD cron && docker-entrypoint.sh redis-server
