FROM redis:latest

RUN apt update
RUN apt install -y python3 python3-pip cron
RUN pip install --upgrade pip

RUN pip install redis
RUN pip install requests
RUN pip install psutil

COPY ./system_health/ /system_health/


COPY ./system_health/crontabs/crontab.redis /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab
RUN crontab /etc/cron.d/crontab
RUN touch /var/log/cron_redis.log


CMD cron && docker-entrypoint.sh redis-server