FROM dfirkuiper/dfir_kuiper:2.2.0

WORKDIR /app

EXPOSE $FLASK_PORT


COPY ./system_health/ /system_health/

COPY ./system_health/crontabs/crontab.flask /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab
RUN crontab /etc/cron.d/crontab
RUN touch /var/log/cron_flask.log

CMD cron && gunicorn --bind $FLASK_IP:$FLASK_PORT Kuiper:app --worker-class $GUNICORN_WORKER_CLASS --workers=$GUNICORN_WORKERS --threads=$GUNICORN_THREADS --timeout=$GUNICORN_TIMEOUT -p "$GUNICORN_PID" --reload
